In [ ]:
###Current clustering goes like
#run_nbs => nbs_cc_main() => hmat_to_cc_cluster() => the 'label' functions
#Translation flow
#Top to bottom, starting with nbs_cc_main()
#1. Need to linearize the flow
#2. Input run_options, inSMdata, and pNetwork and output a cc_cluster, cc_summary, H, W, sampleData, propGeno
#3. Focus solely on the pNetwork and the clustering, ignore lines 18-43, which is all NMF

#Down the line, the parameters could be tightened and shortened
#No need for nanadd() since Python already takes care of that

In [156]:
def hmat_to_cc_cluster(cc_type, kvect, H, Nsample_vect, Nind): #Throw in a clustering type, the k value, ...
    assert cc_type == 'Hard' or 'Soft' or 'Corr'     # a vector containing the random permutation that spans from 1 to
    if cc_type == 'Hard':                            # the number of columns in the SM gene data
    elif cc_type == 'Soft':
        label_to_ccmat_hard(label, perm_list, Nind)
    else: # and number of rows in SM gene data 

IndentationError: expected an indented block (<ipython-input-156-c19063451991>, line 4)

In [ ]:
def Soft_Cluster():

In [ ]:
def Corr():

In [5]:
import numpy as np
def label_to_ccmat_hard(label, perm_list, Nind): #copy of the matlab code
    co_cluster = np.empty((Nind,Nind))           #the idea is to initialize a set NANs that will hold the results
    co_cluster[:] = np.NAN()                     #of the hard clustering
    tlabel_full = np.empty((Nind,1))             #The original code utilizes the matlab sort function
    tlabel_full[:] = np.NAN()                    #Trying to sort from least to greatest on the columns
    matlab_sort_by_column(perm_list)
    

In [60]:
a = np.array([[3,2,1],[5,4,6],[8,1,6],[4,6,8]])
def matlab_sort_by_column(matrix): #This function is supposed to track how the columns of each matrix is sorted
    q = np.sort(matrix,axis=0)
    z = np.empty([len(matrix[:,0]),len(matrix[0,:])]) #Works, but some trouble with duplicate numbers. Should be okay.
    for j in range(len(matrix[0,:])):
        for k in range(len(matrix[:,0])):            
            z[k,j] = list(q[:,j]).index(matrix[k,j])
            print z[:,2]
    return z
    return q
    #print matrix

[ 0.  1.  1.  3.]
[ 0.  1.  1.  3.]
[ 0.  1.  1.  3.]
[ 0.  1.  1.  3.]
[ 0.  1.  1.  3.]
[ 0.  1.  1.  3.]
[ 0.  1.  1.  3.]
[ 0.  1.  1.  3.]
[ 0.  1.  1.  3.]
[ 0.  1.  1.  3.]
[ 0.  1.  1.  3.]
[ 0.  1.  1.  3.]
[[ 1.  2.  1.]
 [ 3.  3.  2.]
 [ 4.  1.  2.]
 [ 2.  4.  4.]]


In [63]:
np.NAN + np.NAN

nan

In [3]:
def label_to_ccmat_soft():
    

IndentationError: expected an indented block (<ipython-input-3-2909462299cf>, line 2)

In [ ]:
def label_to_ccmat_corr(H, perm_list, Nind):
    co_cluster = np.empty(Nind, Nind)
    co_luster[:] = np.NAN()